version: "3"

services:
  database:
    container_name: bluecat-db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/:/docker-entrypoint-initdb.d
      - bluecat_db_data:/var/lib/postgresql

  iam:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=${IAM_USER}
      - KEYCLOAK_PASSWORD=${IAM_PASSWORD}
      - DB_VENDOR=postgres
      - DB_ADDR=database
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=keycloak
      - KEYCLOAK_IMPORT=/tmp/bluecat-realm.json
    volumes:
      - ./docker/iam/bluecat-realm.json:/tmp/bluecat-realm.json
    depends_on:
      - database

volumes:
  bluecat_db_data:
