spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/bluecat
    username: dbuser
    password: dbpasswd
  flyway:
    enabled: true
    baseline-version: 1
  jpa:
    show-sql: true

app:
  flyway:
    info: true
    strategy: MIGRATE

logging:
  level:
    org.springframework.web.servlet: debug
    Exposed: debug
#    root: debug
