spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://127.0.0.1:5439/fusee
    username: dbuser
    password: fuseE3000!
  flyway:
    enabled: true
    baseline-version: 1
#    ANTI-PATTERN ! --> todo: make Transaction Manager work
#  jpa:
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true


app:
  flyway:
    info: true
    strategy: MIGRATE

logging:
  level:
    org.springframework.web.servlet: debug
    Exposed: debug
#    root: debug
